version: '3'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        networks:
            - app-network

    redis:
        image: redis:latest
        restart: unless-stopped
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
